language: python
sudo: false
python:
    - 2.7
install:
    - pip install setuptools==39.0.1
    - python bootstrap.py
    - bin/buildout
script:
    - bin/test
cache:
  pip: true
  directories:
    - eggs/
